<?php
declare(strict_types=1);

/**
 * Backup/Restore helpers for MySQL via PDO.
 * Designed to dump & restore ONLY databases used by this app.
 */

/** @return array<int,string> */
function backup_tables_list(PDO $pdo): array
{
    $tables = [];
    $rows = $pdo->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'")->fetchAll();
    foreach ($rows as $r) {
        if (!is_array($r) || empty($r)) {
            continue;
        }
        // The table name column is driver-dependent, use first value.
        $name = (string)array_values($r)[0];
        $name = trim($name);
        if ($name !== '') {
            $tables[] = $name;
        }
    }
    sort($tables);
    return $tables;
}

function backup_dump_database(PDO $pdo, string $dbName, ?array $tables = null): string
{
    $dbName = trim($dbName);
    if ($dbName === '') {
        throw new RuntimeException('DB name ไม่ถูกต้อง');
    }

    $out = '';
    $out .= "-- SUKHON_TRACK_BACKUP v1\n";
    $out .= "-- Database: {$dbName}\n";
    $out .= "-- Generated at: " . date('c') . "\n\n";
    $out .= "SET NAMES utf8mb4;\n";
    $out .= "SET time_zone = '+00:00';\n";
    $out .= "SET FOREIGN_KEY_CHECKS=0;\n";
    $out .= "\n";

    $out .= "-- USE `{$dbName}`;\n\n";

    if ($tables === null) {
        $tables = backup_tables_list($pdo);
    }

    foreach ($tables as $t) {
        $t = trim((string)$t);
        if ($t === '') continue;

        $stmt = $pdo->query('SHOW CREATE TABLE `' . str_replace('`', '``', $t) . '`');
        $row = $stmt->fetch();
        $createSql = '';
        if (is_array($row)) {
            $vals = array_values($row);
            $createSql = (string)($vals[1] ?? '');
        }

        $out .= "-- ----------------------------\n";
        $out .= "-- Table structure for `{$t}`\n";
        $out .= "-- ----------------------------\n";
        $out .= "DROP TABLE IF EXISTS `{$t}`;\n";
        $out .= $createSql . ";\n\n";

        $out .= "-- ----------------------------\n";
        $out .= "-- Records of `{$t}`\n";
        $out .= "-- ----------------------------\n";

        $stmtCols = $pdo->query('SHOW COLUMNS FROM `' . str_replace('`', '``', $t) . '`');
        $cols = [];
        foreach ($stmtCols->fetchAll() as $c) {
            $cols[] = (string)($c['Field'] ?? '');
        }
        $cols = array_values(array_filter(array_map('trim', $cols), static fn($v) => $v !== ''));
        if (count($cols) === 0) {
            $out .= "\n";
            continue;
        }

        $colListSql = implode(', ', array_map(static fn($c) => '`' . str_replace('`', '``', $c) . '`', $cols));

        $stmtData = $pdo->query('SELECT * FROM `' . str_replace('`', '``', $t) . '`');

        $batch = [];
        $batchMax = 200;

        while (($row = $stmtData->fetch(PDO::FETCH_ASSOC)) !== false) {
            if (!is_array($row)) {
                continue;
            }

            $vals = [];
            foreach ($cols as $c) {
                $v = $row[$c] ?? null;
                if ($v === null) {
                    $vals[] = 'NULL';
                } elseif (is_int($v) || is_float($v)) {
                    $vals[] = (string)$v;
                } else {
                    $vals[] = $pdo->quote((string)$v);
                }
            }

            $batch[] = '(' . implode(', ', $vals) . ')';
            if (count($batch) >= $batchMax) {
                $out .= 'INSERT INTO `' . $t . '` (' . $colListSql . ") VALUES\n";
                $out .= implode(",\n", $batch) . ";\n";
                $batch = [];
            }
        }

        if (count($batch) > 0) {
            $out .= 'INSERT INTO `' . $t . '` (' . $colListSql . ") VALUES\n";
            $out .= implode(",\n", $batch) . ";\n";
        }

        $out .= "\n";
    }

    $out .= "SET FOREIGN_KEY_CHECKS=1;\n";
    return $out;
}

/**
 * Split SQL into statements. Handles quotes/backticks and comments for dumps generated by this app.
 * @return array<int,string>
 */
function backup_sql_split_statements(string $sql): array
{
    $statements = [];
    $buf = '';

    $len = strlen($sql);
    $inSingle = false;
    $inDouble = false;
    $inBacktick = false;
    $inLineComment = false;
    $inBlockComment = false;

    for ($i = 0; $i < $len; $i++) {
        $ch = $sql[$i];
        $next = ($i + 1 < $len) ? $sql[$i + 1] : '';

        if ($inLineComment) {
            if ($ch === "\n") {
                $inLineComment = false;
            }
            $buf .= $ch;
            continue;
        }

        if ($inBlockComment) {
            $buf .= $ch;
            if ($ch === '*' && $next === '/') {
                $buf .= '/';
                $i++;
                $inBlockComment = false;
            }
            continue;
        }

        // Start comments (only when not inside quotes)
        if (!$inSingle && !$inDouble && !$inBacktick) {
            if ($ch === '-' && $next === '-') {
                $inLineComment = true;
                $buf .= $ch;
                continue;
            }
            if ($ch === '#') {
                $inLineComment = true;
                $buf .= $ch;
                continue;
            }
            if ($ch === '/' && $next === '*') {
                $inBlockComment = true;
                $buf .= $ch;
                continue;
            }
        }

        // Quote toggles
        if (!$inDouble && !$inBacktick && $ch === "'" ) {
            // skip escaped quote
            $prev = ($i > 0) ? $sql[$i - 1] : '';
            if ($prev !== '\\') {
                $inSingle = !$inSingle;
            }
        } elseif (!$inSingle && !$inBacktick && $ch === '"') {
            $prev = ($i > 0) ? $sql[$i - 1] : '';
            if ($prev !== '\\') {
                $inDouble = !$inDouble;
            }
        } elseif (!$inSingle && !$inDouble && $ch === '`') {
            $inBacktick = !$inBacktick;
        }

        if (!$inSingle && !$inDouble && !$inBacktick && $ch === ';') {
            $buf .= $ch;
            $trim = trim($buf);
            if ($trim !== '' && $trim !== ';') {
                $statements[] = $trim;
            }
            $buf = '';
            continue;
        }

        $buf .= $ch;
    }

    $trim = trim($buf);
    if ($trim !== '' && $trim !== ';') {
        $statements[] = $trim;
    }

    return $statements;
}

function backup_restore_apply_sql(PDO $pdo, string $sql, string $targetDbName): int
{
    $targetDbName = trim($targetDbName);
    if ($targetDbName === '') {
        throw new RuntimeException('DB เป้าหมายไม่ถูกต้อง');
    }

    // Safety: block dangerous statements
    $danger = ['DROP DATABASE', 'CREATE USER', 'GRANT ', 'REVOKE ', 'FLUSH ', 'SET GLOBAL', 'INTO OUTFILE', 'LOAD DATA', 'LOAD_FILE'];
    $upper = strtoupper($sql);
    foreach ($danger as $kw) {
        if (str_contains($upper, $kw)) {
            throw new RuntimeException('ไฟล์ SQL มีคำสั่งที่ไม่อนุญาต: ' . $kw);
        }
    }

    // Optional header check
    if (!str_contains($sql, 'SUKHON_TRACK_BACKUP v1')) {
        throw new RuntimeException('ไฟล์นี้ไม่ใช่ไฟล์ backup ที่สร้างจากระบบ (SUKHON_TRACK_BACKUP v1)');
    }

    $stmts = backup_sql_split_statements($sql);
    if (count($stmts) === 0) {
        throw new RuntimeException('ไม่พบคำสั่ง SQL ในไฟล์');
    }

    // Ensure we are on intended DB
    $pdo->exec('USE `' . str_replace('`', '``', $targetDbName) . '`');

    $executed = 0;
    foreach ($stmts as $s) {
        $s = trim($s);
        if ($s === '' || $s === ';') continue;

        // Skip commented USE hint
        if (preg_match('/^--\s*USE\b/i', $s)) {
            continue;
        }

        $pdo->exec($s);
        $executed++;
    }

    return $executed;
}
